# Generated by Django 3.0 on 2020-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_auto_20200113_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Fantastyka', 'Fantastyka'), ('Science-fiction', 'Science-fiction'), ('Obyczajowe', 'Obyczajowe'), ('Biografia', 'Biografia'), ('Reportaż', 'Reportaż'), ('Popularnon', 'Popularnon')], max_length=40),
        ),
    ]
