# Generated by Django 3.0 on 2020-01-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_auto_20200113_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_books',
        ),
    ]
